AutoSiteProject/AutoSiteProject.UI/Controllers/CarItemController.cs
using AutoSiteProject.Models.DB;
using AutoSiteProject.Models.ViewModels;
using System.Linq;
using System.Web.Mvc;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using System;
using AutoSiteProject.Models.Bl.Interfaces.Managers;
using AutoSiteProject.UI.Hubs;
using System.Web;
using System.Collections.Generic;
using System.Security;
using System.Text;
using Microsoft.AspNet.Identity;

namespace AutoSiteProject.UI.Controllers
{
    [Authorize]
    public class CarItemController : BaseController
    {
        private readonly ICarItemManager _carItemManager;
        private readonly ICarItemFieldCopier _carItemFieldCopier;
        private readonly ICarOptionManager _carOptionsManager;
        private readonly ICarOptionFieldCopier _carOptionFieldCopier;
        private readonly ICarImageManager _carImageManager;
        private readonly ICarImageFieldCopier _carImageFieldCopier;
        private readonly ICarBodyTypeManager _carBodyTypeManager;
        private readonly ICarModelManager _carModelManager;
        private readonly IManufacturerManager _manufacturerManager;
        public CarItemController(
            ICarItemManager carItemManager,
            ICarItemFieldCopier carItemFieldCopier,
            ICarOptionManager carOptionsManager,
            ICarOptionFieldCopier carOptionFieldCopier,
            ICarImageManager carImageManager,
            ICarImageFieldCopier carImageFieldCopier,
            ICarBodyTypeManager carBodyTypeManager,
            ICarModelManager carModelManager,
            IManufacturerManager manufacturerManager
            )
        {
            _carItemManager = carItemManager;
            _carItemFieldCopier = carItemFieldCopier;
            _carOptionsManager = carOptionsManager;
            _carOptionFieldCopier = carOptionFieldCopier;
            _carImageManager = carImageManager;
            _carImageFieldCopier = carImageFieldCopier;
            _carBodyTypeManager = carBodyTypeManager;
            _carModelManager = carModelManager;
            _manufacturerManager = manufacturerManager;
        }

        // GET
        [AllowAnonymous]
        public ActionResult List()
        {
            return View();
        }

        public ActionResult MyCarsList()
        {
            return View();
        }

        public ActionResult Create(CarItemViewModel model)
        {
            var dbOptions = _carOptionsManager.GetAll().ToList();
            foreach (var item in dbOptions)
            {
                model.AvalibleCarOptions.Add(_carOptionFieldCopier.CopyFields(item, new CarOptionViewModel()));
            }
            ModelState.Clear();
            return View(model);
        }

        private void SaveImagesAndLink(CarItem dbModel, IEnumerable<HttpPostedFileBase> files)
        {
            //save images into db
            if (files == null) return;
            foreach (var file in files)
            {
                if (file == null || file.ContentLength <= 0) continue;
                var image = new CarImages
                {
                    Name = file.FileName,
                    ContentLength = file.ContentLength,
                    ContentType = file.ContentType,
                    Data = new byte[file.ContentLength]
                };
                file.InputStream.Read(image.Data, 0, (int)image.ContentLength);
                _carImageManager.Add(image);//save image to db
                dbModel.CarImages.Add(image); //add link to CarItem 
            }
        }

        //Post
        [HttpPost]
        public ActionResult CreateCar(CarItemViewModel model, List<HttpPostedFileBase> files)
        {
            var userId = User.Identity.GetUserId();
            if (!ModelState.IsValid) return View("Create", model);
            var dbItem = _carItemFieldCopier.CopyFields(model, new CarItem());
            SaveImagesAndLink(dbItem, files);

            dbItem.OwnerId = userId;
            dbItem.LastEditorId = userId;
            dbItem.EditDate = DateTime.Now;
            dbItem.Status = (int)CarItemStatus.Open;

            //add new car into db
            _carItemManager.Add(dbItem);
            //notify all users
            var sb = new StringBuilder();
            if (dbItem.ModelId != null) dbItem.CarModel = _carModelManager.GetById((int)dbItem.ModelId);
            if (dbItem.BodyTypeId != null) dbItem.CarBodyType = _carBodyTypeManager.GetById((int) dbItem.BodyTypeId);
            if (dbItem.ModelId != null && dbItem.CarModel?.ManufacturerId != null)
                dbItem.CarModel.Manufacturer = _manufacturerManager.GetById((int) dbItem.CarModel.ManufacturerId);
            sb.AppendFormat($"Added : {dbItem.CarModel?.Manufacturer?.Name}");
            sb.AppendFormat($" {dbItem.CarModel?.Name}");
            sb.AppendFormat($" {dbItem.CarBodyType?.Name}");
            sb.AppendFormat($" {dbItem.ReleaseYear}r.y.");
            sb.AppendFormat($" {dbItem.Price}$");
            NotificationsHub.SendInfoMessage(sb.ToString());
            return RedirectToAction("List");
        }

        //GET 
        public ActionResult Edit(int id)
        {
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();

            if (!User.IsInRole("Admin"))
            {
                var userId = User.Identity.GetUserId();
                if (dbItem.Status != (int)CarItemStatus.Open) throw new SecurityException();
                if (dbItem.OwnerId != userId) throw new SecurityException();
            }

            var result = _carItemFieldCopier.CopyFields(dbItem, new CarItemViewModel());
            foreach (var image in dbItem.CarImages)
            {
                result.Images.Add(_carImageFieldCopier.CopyFields(image, new CarImageViewModel()));//copy all without data
            }
            var dbOptions = _carOptionsManager.GetAll().ToList();
            foreach (var item in dbOptions)
            {
                result.AvalibleCarOptions.Add(_carOptionFieldCopier.CopyFields(item, new CarOptionViewModel()));
            }
            return View(result);
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();

            var result = _carItemFieldCopier.CopyFields(dbItem, new CarItemViewModel());

            if (result.SelectedCarOptions != null)
                for (var i = 0; i < result.SelectedCarOptions.Length; i++)
                    result.SelectedCarOptions[i] = _carOptionsManager.GetById(int.Parse(result.SelectedCarOptions[i])).Name;
            foreach (var image in dbItem.CarImages)
            {
                var img = _carImageFieldCopier.CopyFields(image, new CarImageViewModel());
                img.Data = image.Data;
                result.Images.Add(img);

            }
            return View(result);
        }

        //Post
        [HttpPost]
        public ActionResult Edit(CarItemViewModel model, List<HttpPostedFileBase> files)
        {
            if (!ModelState.IsValid) return View(model);
            var userId = User.Identity.GetUserId();
            var dbItem = _carItemManager.GetById(model.Id);
            if (dbItem == null) throw new NullReferenceException();
            if (!User.IsInRole("Admin"))
            {
                if (dbItem.Status != (int)CarItemStatus.Open) throw new SecurityException();
                if (dbItem.OwnerId != userId) throw new SecurityException();
            }
            //delete disabled images
            var dbImagesIds = dbItem.CarImages.Select(x => x.Id);
            var modelImagesIds = model.Images.Select(x => x.Id);
            var imagesIdsForDelete = dbImagesIds.Except(modelImagesIds);
            DeleteImages(dbItem, imagesIdsForDelete);
            //add new images
            SaveImagesAndLink(dbItem, files);
            //copy edited fields
            dbItem = _carItemFieldCopier.CopyFields(model, dbItem);
            //edit options
            dbItem.LastEditorId = userId;
            dbItem.EditDate = DateTime.Now;
            //save changes
            _carItemManager.Edit(dbItem);
            return RedirectToAction("List");
        }

        private void DeleteImages(CarItem dbItem, IEnumerable<int> ids)
        {
            var dbImagesArrayForDelete = dbItem.CarImages.Where(x => ids.Contains(x.Id)).ToList();
            foreach (var item in dbImagesArrayForDelete)
            {
                //remove from dbitem
                dbItem.CarImages.Remove(item);
                //remove from database
                _carImageManager.Delete(item);
            }
        }

        //GET 
        public ActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin")) throw new SecurityException();//only admin can delete
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            _carItemManager.Delete(dbItem);
            return RedirectToAction("List");
        }
        //GET 
        public ActionResult SetStatusToClose(int id)
        {
            var userId = User.Identity.GetUserId();
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            if (!User.IsInRole("Admin"))
            {
                if (dbItem.OwnerId != userId) throw new SecurityException();
            }
            dbItem.LastEditorId = userId;
            dbItem.EditDate = DateTime.Now;
            dbItem.Status = (int)CarItemStatus.Closed;
            _carItemManager.Edit(dbItem);
            return Redirect(Request.UrlReferrer?.ToString());
        }
    }
}

AutoSiteProject/AutoSiteProject.UI/Controllers/RoleController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using AutoSiteProject.Models.DB;
using AutoSiteProject.Models.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using AutoSiteProject.Bl.IdentityClasses;

namespace AutoSiteProject.UI.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "Admin")]
    public class RoleController : BaseController
    {
        private readonly IRoleFieldCopier _roleFieldCopier;
        public RoleController(IRoleFieldCopier roleFieldCopier)
        {
            _roleFieldCopier = roleFieldCopier;
        }

        public ApplicationRoleManager RoleManager => HttpContext.GetOwinContext().Get<ApplicationRoleManager>();


        // GET: Role
        public ActionResult List()
        {
            //var dbRoles = RoleManager.Roles.ToList();
            //var rolesViewModels = dbRoles.Select(r => _roleFieldCopier.CopyFields(r, new RoleViewModel())).ToList();
            return View();//rolesViewModels);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                // Initialize ApplicationRole instead of IdentityRole:
                var role = _roleFieldCopier.CopyFields(roleViewModel, new ApplicationRole());
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("List");
            }
            return View();
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null) return HttpNotFound();
            var roleModel = _roleFieldCopier.CopyFields(role, new RoleViewModel());
            return View(roleModel);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleViewModel.Id);
                if (role == null) return HttpNotFound();
                role = _roleFieldCopier.CopyFields(roleViewModel, role);
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("List");
            }
            return View();
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null) return HttpNotFound();
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("List");
        }

    }
}

AutoSiteProject/AutoSiteProject.UI/Controllers/UserController.cs
using AutoSiteProject.Bl.IdentityClasses;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using AutoSiteProject.Models.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Data.Entity.Core;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace AutoSiteProject.UI.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "Admin")]
    public class UserController : BaseController
    {
        
        private readonly IUserFieldCopier _userFieldCopier;
        private readonly IRoleFieldCopier _roleFieldCopier;
        public UserController(IUserFieldCopier userFieldCopier, IRoleFieldCopier roleFieldCopier)
        {
            _userFieldCopier = userFieldCopier;
            _roleFieldCopier = roleFieldCopier;
        }
        public ApplicationRoleManager RoleManager =>  HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
        public ApplicationUserManager UserManager =>  HttpContext.GetOwinContext().Get<ApplicationUserManager>();

        public async Task<ActionResult> List()
        {
            var usersViewModels = new List<UserViewModel>();
            var dbUsers = UserManager.Users.ToList();
            foreach (var u in dbUsers)
            {
                var q = _userFieldCopier.CopyFields(u, new UserViewModel());
                for (int i = 0; i < q.SelectedRoles.Length; i++)
                {
                    q.SelectedRoles[i] = (await RoleManager.FindByIdAsync(q.SelectedRoles[i])).Name;
                }
                usersViewModels.Add(q);
            }
            return View(usersViewModels);
        }
        public ActionResult Edit(string id)
        {
            var dbUser = UserManager.Users.FirstOrDefault(u => u.Id == id);
            if (dbUser == null) throw new ObjectNotFoundException();
            var userViewModel = _userFieldCopier.CopyFields(dbUser, new UserViewModel());
            var dbRoles = RoleManager.Roles.ToList();
            foreach (var item in dbRoles)
            {
                userViewModel.AvalibleRoles.Add(_roleFieldCopier.CopyFields(item, new RoleViewModel()));
            }
            return View(userViewModel);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                var dbUser = UserManager.Users.FirstOrDefault(u => u.Id == userViewModel.Id);
                if (dbUser == null) throw new ObjectNotFoundException();
                dbUser = _userFieldCopier.CopyFields(userViewModel, dbUser);
                await UserManager.UpdateAsync(dbUser);

                var userRolesToDelete = UserManager.GetRoles(dbUser.Id);

                foreach (var roleId in userViewModel.SelectedRoles)
                {
                    var role = RoleManager.FindById(roleId);
                    if (userRolesToDelete.Contains(role.Name))
                        userRolesToDelete.RemoveAt(userRolesToDelete.IndexOf(role.Name));
                    UserManager.AddToRole(dbUser.Id, role.Name);
                }
                foreach (var roleName in userRolesToDelete)
                {
                    UserManager.RemoveFromRole(dbUser.Id, roleName);
                }

                return RedirectToAction("List");
            }
            return View();
        }

        public ActionResult Delete(string id)
        {
            UserManager.Delete(UserManager.FindById(id));
            return RedirectToAction("List");
        }
    }
}

AutoSiteProject/AutoSiteProject.UI/Views/Shared/_Layout.cshtml
@using AutoSiteProject.UI.Helpers
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AutoSiteProject</title>
    <link href="~/Content/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/MyCss/LayoutStyles.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/scripts/modernizr-2.7.2.js"></script>
    @Html.DevExpress().GetScripts(
        //new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        //new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
        //new Script { ExtensionSuite = ExtensionSuite.Editors },
        //new Script { ExtensionSuite = ExtensionSuite.Chart },
        //new Script { ExtensionSuite = ExtensionSuite.Report },
        new Script { ExtensionSuite = ExtensionSuite.Scheduler },
        //new Script { ExtensionSuite = ExtensionSuite.TreeList },
        //new Script { ExtensionSuite = ExtensionSuite.Spreadsheet },
        //new Script { ExtensionSuite = ExtensionSuite.RichEdit },
        //new Script { ExtensionSuite = ExtensionSuite.SpellChecker },
        new Script { ExtensionSuite = ExtensionSuite.GridView }

    )
    @Html.DevExpress().GetStyleSheets(
        //new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler, Theme = "Moderno" },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.SpellChecker },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView, Theme = "Moderno" }

    )
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="~/scripts/select2.min.js"></script>
    <script src="~/scripts/AutoSite/MySelect2Search.js"></script>
    <script src="~/scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/scripts/AutoSite/Notifications.js"></script>
    <script src="~/scripts/jquery-ui-1.12.0.min.js"></script>
    <link href="~/Content/MyCss/WidthClasses.css" rel="stylesheet" />
    <link href="~/Content/MyCss/Select2Styles.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "" })</li>
                <li>@Html.ActionLink("Cars", "List", "CarItem", new { area = "" }, new { @class = "" })</li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("My cars", "MyCarsList", "CarItem", new { area = "", id = User.Identity.GetUserId() }, new { @class = "" })</li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Managment<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Car models", "List", "CarModel", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Car body types", "List", "CarBodyType", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Car options", "List", "CarOption", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Manufacturers", "List", "Manufacturer", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Countries", "List", "Country", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Car fuel types", "List", "FuelType", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Car transmition types", "List", "TransmitionType", new { area = "" }, new { @class = "" })</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Users", "List", "User", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Roles", "List", "Role", new { area = "" }, new { @class = "" })</li>
                        </ul>
                    </li>
                }
                <li>
                    @Html.Select2Search(new { @class = "select2Search" })
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="notifications">
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year - AutoSiteProject</p>
        </footer>
    </div>
</body>
</html>