AutoSiteProject/AutoSiteProject.UI/Controllers/CarModelController.cs
using AutoSiteProject.Models.DB;
using AutoSiteProject.Models.ViewModels;
using System.Linq;
using System.Web.Mvc;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using System;
using AutoSiteProject.Models.Bl.Interfaces.Managers;

namespace AutoSiteProject.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarModelController : BaseController
    {
        private readonly ICarModelManager _carModelManager;
        private readonly IManufacturerManager _manufacturerManager;
        private readonly ICarModelFieldCopier _carModelFieldCopier;

        public CarModelController(ICarModelManager carModelManager,
            IManufacturerManager manufacturerManager,
            ICarModelFieldCopier carModelFieldCopier)
        {
            _manufacturerManager = manufacturerManager;
            _carModelManager = carModelManager;
            _carModelFieldCopier = carModelFieldCopier;
        }

        // GET: CarModel
        public ActionResult List()
        {
            return View();
        }

        //GET 
        public ActionResult Create()
        {
            ViewBag.Manufacturers = new SelectList(_manufacturerManager.GetAll().ToList(), "Id", "Name");
            return View();
        }
        //Post
        [HttpPost]
        public ActionResult Create(CarModelViewModel model)
        {
            if (ModelState.IsValid)
            {
                _carModelManager.Add(_carModelFieldCopier.CopyFields(model, new CarModel()));
                return RedirectToAction("List");
            }
            return View(model);
        }

        //GET 
        public ActionResult Edit(int id)
        {
            var dbItem = _carModelManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            ViewBag.Manufacturers = new SelectList(_manufacturerManager.GetAll().ToList(), "Id", "Name");
            return View(_carModelFieldCopier.CopyFields(dbItem, new CarModelViewModel()));
        }
        //Post
        [HttpPost]
        public ActionResult Edit(CarModelViewModel model)
        {
            if (ModelState.IsValid)
            {
                var dbItem = _carModelManager.GetById(model.Id);
                if (dbItem == null) throw new NullReferenceException();
                dbItem = _carModelFieldCopier.CopyFields(model, dbItem);
                _carModelManager.Edit(dbItem);
                return RedirectToAction("List");
            }
            return View(model);
        }

        //GET 
        public ActionResult Delete(int id)
        {
            var dbItem = _carModelManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            _carModelManager.Delete(dbItem);
            return RedirectToAction("List");
        }
    }
}

AutoSiteProject/AutoSiteProject.UI/Controllers/DataLoaderController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoSiteProject.Models.ViewModels;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using AutoSiteProject.Models.Bl.Interfaces.Managers;
using AutoSiteProject.Bl.IdentityClasses;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace AutoSiteProject.UI.Controllers
{
    public class DataLoaderController : BaseController
    {
        private readonly ICarModelManager _carModelManager;
        private readonly IManufacturerManager _manufacturerManager;
        private readonly ICountryManager _countryManager;
        private readonly ICarBodyTypeManager _carBodyTypeManager;
        private readonly ICarOptionManager _carOptionManager;
        private readonly ICarModelFieldCopier _carModelFieldCopier;
        private readonly IManufacturerFieldCopier _manufacturerFieldCopier;
        private readonly ICountryFieldCopier _countryFieldCopier;
        private readonly ICarBodyTypeFieldCopier _carBodyTypeFieldCopier;
        private readonly ICarOptionFieldCopier _carOptionFieldCopier;
        private readonly ICarItemManager _carItemManager;
        private readonly IRoleFieldCopier _roleFieldCopier;
        private readonly IUserFieldCopier _userFieldCopier;
        private readonly ICarImageManager _carImageManager;
        private readonly IFuelTypeManager _fuelTypeManager;
        private readonly IFuelTypeFieldCopier _fuelTypeFieldCopier;
        private readonly ITransmitionTypeManager _transmitionTypeManager;
        private readonly ITransmitionTypeFieldCopier _transmitionTypeFieldCopier;

        public ApplicationRoleManager RoleManager => HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
        public  ApplicationUserManager UserManager => HttpContext.GetOwinContext().Get<ApplicationUserManager>();

        public DataLoaderController(
            ICarModelManager carModelManager,
            IManufacturerManager manufacturerManager,
            ICountryManager countryManager,
            ICarBodyTypeManager carBodyTypeManager,
            ICarOptionManager carOptionManager,
            ICarModelFieldCopier carModelFieldCopier,
            IManufacturerFieldCopier manufacturerFieldCopier,
            ICountryFieldCopier countryFieldCopier,
            ICarBodyTypeFieldCopier carBodyTypeFieldCopier,
            ICarOptionFieldCopier carOptionFieldCopier,
            ICarItemManager carItemManager,
            IRoleFieldCopier roleFieldCopier,
            ICarImageManager carImageManage,
            IUserFieldCopier userFieldCopier, 
            IFuelTypeManager fuelTypeManager,
            IFuelTypeFieldCopier fuelTypeFieldCopier,
            ITransmitionTypeManager transmitionTypeManager,
            ITransmitionTypeFieldCopier transmitionTypeFieldCopier
            )
        {
            _carModelManager = carModelManager;
            _manufacturerManager = manufacturerManager;
            _countryManager = countryManager;
            _carBodyTypeManager = carBodyTypeManager;
            _carOptionManager = carOptionManager;
            _carImageManager = carImageManage;
            _carModelFieldCopier = carModelFieldCopier;
            _manufacturerFieldCopier = manufacturerFieldCopier;
            _countryFieldCopier = countryFieldCopier;
            _carBodyTypeFieldCopier = carBodyTypeFieldCopier;
            _carOptionFieldCopier = carOptionFieldCopier;
            _carItemManager = carItemManager;
            _roleFieldCopier = roleFieldCopier;
            _userFieldCopier = userFieldCopier;
            _fuelTypeManager = fuelTypeManager;
            _fuelTypeFieldCopier = fuelTypeFieldCopier;
            _transmitionTypeManager = transmitionTypeManager;
            _transmitionTypeFieldCopier = transmitionTypeFieldCopier;
        }
        [HttpPost]
        public JsonResult GetCars(CarAggregateFilterViewModel filter)
        {
            if (filter == null) filter = new CarAggregateFilterViewModel();
            var carsList = _carItemManager.GetCarsAggregateViewModel(filter);
            //filter result by status
            var thisIsAdmin = User.IsInRole("Admin");
            carsList = carsList.Where(r => r.Status == CarItemStatus.Open || thisIsAdmin).Take(4).ToList();
            return Json(carsList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCountries()
        {

            var dbItems = _countryManager.GetAll().ToList();
            var result = dbItems.Select(item => _countryFieldCopier.CopyFields(item, new CountryViewModel())).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetManufacturersOfCountry(int id)
        {
            var dbItems = _manufacturerManager.GetAll().Where(m => m.CountryId == id).ToList();
            var result = dbItems.Select(item => _manufacturerFieldCopier.CopyFields(item, new ManufacturerViewModel())).ToList();

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCarModelsOfManufacturer(int id)
        {
            var dbItems = _carModelManager.GetAll().Where(m => m.ManufacturerId == id).ToList();
            var result = dbItems.Select(item => _carModelFieldCopier.CopyFields(item, new CarModelViewModel())).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetBodyTypes()
        {
            var dbItems = _carBodyTypeManager.GetAll().ToList();
            var result = dbItems.Select(item => _carBodyTypeFieldCopier.CopyFields(item, new CarBodyTypeViewModel())).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetFuelTypes()
        {
            var dbItems = _fuelTypeManager.GetAll().ToList();
            var result = dbItems.Select(item => _fuelTypeFieldCopier.CopyFields(item, new FuelTypeViewModel())).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTransmitionTypes()
        {
            var dbItems = _transmitionTypeManager.GetAll().ToList();
            var result = dbItems.Select(item => _transmitionTypeFieldCopier.CopyFields(item, new TransmitionTypeViewModel())).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetOptionsOfCarItem(int id)
        {

            var dbItems = _carOptionManager.GetAll().Where(co => co.CarItem.Any(ci => ci.Id == id)).ToList();
            var result = dbItems.Select(item => _carOptionFieldCopier.CopyFields(item, new CarOptionViewModel())).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCarOptions()
        {
            var dbItems = _carOptionManager.GetAll().ToList();
            var result = dbItems.Select(item => _carOptionFieldCopier.CopyFields(item, new CarOptionViewModel())).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCarsPartial(CarAggregateFilterViewModel filter)
        {
            var carsList = _carItemManager.GetCarsAggregateViewModel(filter);
            //filter result by status
            var thisIsAdmin = User.IsInRole("Admin");
            carsList = carsList.Where(r => r.Status == CarItemStatus.Open || thisIsAdmin).ToList();
            return PartialView("CarsGridViewPartial", carsList);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetCarBodyTypesPartial()
        {
            var dbItems = _carBodyTypeManager.GetAll().ToList();
            var result = dbItems.Select(item => _carBodyTypeFieldCopier.CopyFields(item, new CarBodyTypeViewModel())).ToList();
            return PartialView("GetCarBodyTypesPartial", result);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetCarModelsPartial()
        {
            var dbItems = _carModelManager.GetAll();
            var result = dbItems.Select(item => _carModelFieldCopier.CopyFields(item, new CarModelViewModel())).ToList();
            return PartialView("GetCarModelsPartial", result);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetCarOptionsPartial()
        {
            var dbItems = _carOptionManager.GetAll();
            var result = dbItems.Select(item => _carOptionFieldCopier.CopyFields(item, new CarOptionViewModel())).ToList();
            return PartialView("GetCarOptionsPartial", result);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetCountriesPartial()
        {
            var dbItems = _countryManager.GetAll();
            var result = dbItems.Select(item => _countryFieldCopier.CopyFields(item, new CountryViewModel())).ToList();
            return PartialView("GetCountriesPartial", result);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetManufacturersPartial()
        {
            var dbItems = _manufacturerManager.GetAll();
            var result = dbItems.Select(item => _manufacturerFieldCopier.CopyFields(item, new ManufacturerViewModel())).ToList();
            return PartialView("GetManufacturersPartial", result);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetRolesPartial()
        {
            var dbRoles = RoleManager.Roles.ToList();
            var result = dbRoles.Select(r => _roleFieldCopier.CopyFields(r, new RoleViewModel())).ToList();
            return PartialView("GetRolesPartial", result);
        }
        public ActionResult GetCarItemsPartial()
        {
            var filter = new CarAggregateFilterViewModel
            {
                PriceMax = int.MaxValue,
                ReleaseYearMax = int.MaxValue,
                VolumeMax = int.MaxValue
            };
            var result = _carItemManager.GetCarsAggregateViewModel(filter);
            //filter result by status

AutoSiteProject/AutoSiteProject.UI/Views/CarModel/Create.cshtml
@model AutoSiteProject.Models.ViewModels.CarModelViewModel

<h3>Create car model</h3>
<hr/>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManufacturerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ManufacturerId, (SelectList)ViewBag.Manufacturers, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>


 
 

AutoSiteProject/AutoSiteProject.UI/Views/CarModel/Edit.cshtml
@model AutoSiteProject.Models.ViewModels.CarModelViewModel

<h3>Edit car model</h3>
<hr/>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManufacturerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ManufacturerId, (SelectList)ViewBag.Manufacturers, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>


 
 

AutoSiteProject/AutoSiteProject.UI/Views/CarModel/List.cshtml
@model IEnumerable<AutoSiteProject.Models.ViewModels.CarAggregateViewModel>
    <hr/>
@{ Html.RenderAction("GetCarModelsPartial", "DataLoader"); }