AutoSiteProject/AutoSiteProject.UI/Controllers/CarItemController.cs
using AutoSiteProject.Models.DB;
using AutoSiteProject.Models.ViewModels;
using System.Linq;
using System.Web.Mvc;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using System;
using AutoSiteProject.Models.Bl.Interfaces.Managers;
using AutoSiteProject.UI.Hubs;
using System.Web;
using System.Collections.Generic;
using System.Security;
using System.Text;
using Microsoft.AspNet.Identity;

namespace AutoSiteProject.UI.Controllers
{
    [Authorize]
    public class CarItemController : BaseController
    {
        private readonly ICarItemManager _carItemManager;
        private readonly ICarItemFieldCopier _carItemFieldCopier;
        private readonly ICarOptionManager _carOptionsManager;
        private readonly ICarOptionFieldCopier _carOptionFieldCopier;
        private readonly ICarImageManager _carImageManager;
        private readonly ICarImageFieldCopier _carImageFieldCopier;
        private readonly ICarBodyTypeManager _carBodyTypeManager;
        private readonly ICarModelManager _carModelManager;
        private readonly IManufacturerManager _manufacturerManager;
        public CarItemController(
            ICarItemManager carItemManager,
            ICarItemFieldCopier carItemFieldCopier,
            ICarOptionManager carOptionsManager,
            ICarOptionFieldCopier carOptionFieldCopier,
            ICarImageManager carImageManager,
            ICarImageFieldCopier carImageFieldCopier,
            ICarBodyTypeManager carBodyTypeManager,
            ICarModelManager carModelManager,
            IManufacturerManager manufacturerManager
            )
        {
            _carItemManager = carItemManager;
            _carItemFieldCopier = carItemFieldCopier;
            _carOptionsManager = carOptionsManager;
            _carOptionFieldCopier = carOptionFieldCopier;
            _carImageManager = carImageManager;
            _carImageFieldCopier = carImageFieldCopier;
            _carBodyTypeManager = carBodyTypeManager;
            _carModelManager = carModelManager;
            _manufacturerManager = manufacturerManager;
        }

        // GET
        [AllowAnonymous]
        public ActionResult List()
        {
            return View();
        }

        public ActionResult MyCarsList()
        {
            return View();
        }

        public ActionResult Create(CarItemViewModel model)
        {
            var dbOptions = _carOptionsManager.GetAll().ToList();
            foreach (var item in dbOptions)
            {
                model.AvalibleCarOptions.Add(_carOptionFieldCopier.CopyFields(item, new CarOptionViewModel()));
            }
            ModelState.Clear();
            return View(model);
        }

        private void SaveImagesAndLink(CarItem dbModel, IEnumerable<HttpPostedFileBase> files)
        {
            //save images into db
            if (files == null) return;
            foreach (var file in files)
            {
                if (file == null || file.ContentLength <= 0) continue;
                var image = new CarImages
                {
                    Name = file.FileName,
                    ContentLength = file.ContentLength,
                    ContentType = file.ContentType,
                    Data = new byte[file.ContentLength]
                };
                file.InputStream.Read(image.Data, 0, (int)image.ContentLength);
                _carImageManager.Add(image);//save image to db
                dbModel.CarImages.Add(image); //add link to CarItem 
            }
        }

        //Post
        [HttpPost]
        public ActionResult CreateCar(CarItemViewModel model, List<HttpPostedFileBase> files)
        {
            var userId = User.Identity.GetUserId();
            if (!ModelState.IsValid) return View("Create", model);
            var dbItem = _carItemFieldCopier.CopyFields(model, new CarItem());
            SaveImagesAndLink(dbItem, files);

            dbItem.OwnerId = userId;
            dbItem.LastEditorId = userId;
            dbItem.EditDate = DateTime.Now;
            dbItem.Status = (int)CarItemStatus.Open;

            //add new car into db
            _carItemManager.Add(dbItem);
            //notify all users
            var sb = new StringBuilder();
            if (dbItem.ModelId != null) dbItem.CarModel = _carModelManager.GetById((int)dbItem.ModelId);
            if (dbItem.BodyTypeId != null) dbItem.CarBodyType = _carBodyTypeManager.GetById((int) dbItem.BodyTypeId);
            if (dbItem.ModelId != null && dbItem.CarModel?.ManufacturerId != null)
                dbItem.CarModel.Manufacturer = _manufacturerManager.GetById((int) dbItem.CarModel.ManufacturerId);
            sb.AppendFormat($"Added : {dbItem.CarModel?.Manufacturer?.Name}");
            sb.AppendFormat($" {dbItem.CarModel?.Name}");
            sb.AppendFormat($" {dbItem.CarBodyType?.Name}");
            sb.AppendFormat($" {dbItem.ReleaseYear}r.y.");
            sb.AppendFormat($" {dbItem.Price}$");
            NotificationsHub.SendInfoMessage(sb.ToString());
            return RedirectToAction("List");
        }

        //GET 
        public ActionResult Edit(int id)
        {
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();

            if (!User.IsInRole("Admin"))
            {
                var userId = User.Identity.GetUserId();
                if (dbItem.Status != (int)CarItemStatus.Open) throw new SecurityException();
                if (dbItem.OwnerId != userId) throw new SecurityException();
            }

            var result = _carItemFieldCopier.CopyFields(dbItem, new CarItemViewModel());
            foreach (var image in dbItem.CarImages)
            {
                result.Images.Add(_carImageFieldCopier.CopyFields(image, new CarImageViewModel()));//copy all without data
            }
            var dbOptions = _carOptionsManager.GetAll().ToList();
            foreach (var item in dbOptions)
            {
                result.AvalibleCarOptions.Add(_carOptionFieldCopier.CopyFields(item, new CarOptionViewModel()));
            }
            return View(result);
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();

            var result = _carItemFieldCopier.CopyFields(dbItem, new CarItemViewModel());

            if (result.SelectedCarOptions != null)
                for (var i = 0; i < result.SelectedCarOptions.Length; i++)
                    result.SelectedCarOptions[i] = _carOptionsManager.GetById(int.Parse(result.SelectedCarOptions[i])).Name;
            foreach (var image in dbItem.CarImages)
            {
                var img = _carImageFieldCopier.CopyFields(image, new CarImageViewModel());
                img.Data = image.Data;
                result.Images.Add(img);

            }
            return View(result);
        }

        //Post
        [HttpPost]
        public ActionResult Edit(CarItemViewModel model, List<HttpPostedFileBase> files)
        {
            if (!ModelState.IsValid) return View(model);
            var userId = User.Identity.GetUserId();
            var dbItem = _carItemManager.GetById(model.Id);
            if (dbItem == null) throw new NullReferenceException();
            if (!User.IsInRole("Admin"))
            {
                if (dbItem.Status != (int)CarItemStatus.Open) throw new SecurityException();
                if (dbItem.OwnerId != userId) throw new SecurityException();
            }
            //delete disabled images
            var dbImagesIds = dbItem.CarImages.Select(x => x.Id);
            var modelImagesIds = model.Images.Select(x => x.Id);
            var imagesIdsForDelete = dbImagesIds.Except(modelImagesIds);
            DeleteImages(dbItem, imagesIdsForDelete);
            //add new images
            SaveImagesAndLink(dbItem, files);
            //copy edited fields
            dbItem = _carItemFieldCopier.CopyFields(model, dbItem);
            //edit options
            dbItem.LastEditorId = userId;
            dbItem.EditDate = DateTime.Now;
            //save changes
            _carItemManager.Edit(dbItem);
            return RedirectToAction("List");
        }

        private void DeleteImages(CarItem dbItem, IEnumerable<int> ids)
        {
            var dbImagesArrayForDelete = dbItem.CarImages.Where(x => ids.Contains(x.Id)).ToList();
            foreach (var item in dbImagesArrayForDelete)
            {
                //remove from dbitem
                dbItem.CarImages.Remove(item);
                //remove from database
                _carImageManager.Delete(item);
            }
        }

        //GET 
        public ActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin")) throw new SecurityException();//only admin can delete
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            _carItemManager.Delete(dbItem);
            return RedirectToAction("List");
        }
        //GET 
        public ActionResult SetStatusToClose(int id)
        {
            var userId = User.Identity.GetUserId();
            var dbItem = _carItemManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            if (!User.IsInRole("Admin"))
            {
                if (dbItem.OwnerId != userId) throw new SecurityException();
            }
            dbItem.LastEditorId = userId;
            dbItem.EditDate = DateTime.Now;
            dbItem.Status = (int)CarItemStatus.Closed;
            _carItemManager.Edit(dbItem);
            return Redirect(Request.UrlReferrer?.ToString());
        }
    }
}

AutoSiteProject/AutoSiteProject.UI/Controllers/CarModelController.cs
using AutoSiteProject.Models.DB;
using AutoSiteProject.Models.ViewModels;
using System.Linq;
using System.Web.Mvc;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using System;
using AutoSiteProject.Models.Bl.Interfaces.Managers;

namespace AutoSiteProject.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarModelController : BaseController
    {
        private readonly ICarModelManager _carModelManager;
        private readonly IManufacturerManager _manufacturerManager;
        private readonly ICarModelFieldCopier _carModelFieldCopier;

        public CarModelController(ICarModelManager carModelManager,
            IManufacturerManager manufacturerManager,
            ICarModelFieldCopier carModelFieldCopier)
        {
            _manufacturerManager = manufacturerManager;
            _carModelManager = carModelManager;
            _carModelFieldCopier = carModelFieldCopier;
        }

        // GET: CarModel
        public ActionResult List()
        {
            return View();
        }

        //GET 
        public ActionResult Create()
        {
            ViewBag.Manufacturers = new SelectList(_manufacturerManager.GetAll().ToList(), "Id", "Name");
            return View();
        }
        //Post
        [HttpPost]
        public ActionResult Create(CarModelViewModel model)
        {
            if (ModelState.IsValid)
            {
                _carModelManager.Add(_carModelFieldCopier.CopyFields(model, new CarModel()));
                return RedirectToAction("List");
            }
            return View(model);
        }

        //GET 
        public ActionResult Edit(int id)
        {
            var dbItem = _carModelManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            ViewBag.Manufacturers = new SelectList(_manufacturerManager.GetAll().ToList(), "Id", "Name");
            return View(_carModelFieldCopier.CopyFields(dbItem, new CarModelViewModel()));
        }
        //Post
        [HttpPost]
        public ActionResult Edit(CarModelViewModel model)
        {
            if (ModelState.IsValid)
            {
                var dbItem = _carModelManager.GetById(model.Id);
                if (dbItem == null) throw new NullReferenceException();
                dbItem = _carModelFieldCopier.CopyFields(model, dbItem);
                _carModelManager.Edit(dbItem);
                return RedirectToAction("List");
            }
            return View(model);
        }

        //GET 
        public ActionResult Delete(int id)
        {
            var dbItem = _carModelManager.GetById(id);
            if (dbItem == null) throw new NullReferenceException();
            _carModelManager.Delete(dbItem);
            return RedirectToAction("List");
        }
    }
}

AutoSiteProject/AutoSiteProject.UI/Controllers/RoleController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoSiteProject.Models.Bl.Interfaces.FieldCopiers;
using AutoSiteProject.Models.DB;
using AutoSiteProject.Models.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using AutoSiteProject.Bl.IdentityClasses;

namespace AutoSiteProject.UI.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "Admin")]
    public class RoleController : BaseController
    {
        private readonly IRoleFieldCopier _roleFieldCopier;
        public RoleController(IRoleFieldCopier roleFieldCopier)
        {
            _roleFieldCopier = roleFieldCopier;
        }

        public ApplicationRoleManager RoleManager => HttpContext.GetOwinContext().Get<ApplicationRoleManager>();


        // GET: Role
        public ActionResult List()
        {
            //var dbRoles = RoleManager.Roles.ToList();
            //var rolesViewModels = dbRoles.Select(r => _roleFieldCopier.CopyFields(r, new RoleViewModel())).ToList();
            return View();//rolesViewModels);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                // Initialize ApplicationRole instead of IdentityRole:
                var role = _roleFieldCopier.CopyFields(roleViewModel, new ApplicationRole());
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("List");
            }
            return View();
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null) return HttpNotFound();
            var roleModel = _roleFieldCopier.CopyFields(role, new RoleViewModel());
            return View(roleModel);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleViewModel.Id);
                if (role == null) return HttpNotFound();
                role = _roleFieldCopier.CopyFields(roleViewModel, role);
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("List");
            }
            return View();
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null) return HttpNotFound();
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("List");
        }

    }
}

AutoSiteProject/AutoSiteProject.UI/Views/DataLoader/CarsGridViewPartial.cshtml
@using System.Web.UI.WebControls
@using AutoSiteProject.Models.ViewModels
@using Microsoft.AspNet.Identity
@model IEnumerable<CarAggregateViewModel>

@Html.DevExpress().GridView(settings =>
{
    settings.Name = "carsGridView";
    settings.CallbackRouteValues = new { Controller = "DataLoader", Action = "GetCarsPartial" };
    settings.Width = Unit.Percentage(100);

    if (User.IsInRole("Admin")) settings.Columns.Add("CarId");

    settings.Columns.Add("Country");
    settings.Columns.Add("Manufacturer");
    settings.Columns.Add("Model"); 
    settings.Columns.Add("BodyType", "Body type");
    settings.Columns.Add("FuelType", "Fuel type");
    settings.Columns.Add("TransmitionType", "Transmition type");
    settings.Columns.Add("Price");
    settings.Columns.Add("ReleaseYear", "Release year");
    settings.Columns.Add("Volume", "Engine volume");
    settings.Columns.Add("Description");
    settings.Columns.Add("OptionsNamesString", "Options");
    if (User.IsInRole("Admin")) settings.Columns.Add("Status");
    settings.Columns.Add(column =>
    {
        column.Caption = "#";
        column.SetDataItemTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("Details", "Details", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                + "&nbsp;");
            var userId = User.Identity.GetUserId();
            if ((DataBinder.Eval(c.DataItem, "OwnerId").ToString() == userId && ((CarItemStatus)DataBinder.Eval(c.DataItem, "Status")) == CarItemStatus.Open) || User.IsInRole("Admin"))
                ViewContext.Writer.Write(
                        Html.ActionLink("Edit", "Edit", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        + "&nbsp;" +
                        Html.ActionLink("Close", "SetStatusToClose", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        );
            if (User.IsInRole("Admin"))
                ViewContext.Writer.Write(
                        "&nbsp;" +
                        Html.ActionLink("Delete", "Delete", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        );
        });
        column.SetHeaderTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("New", "Create", "CarItem").ToHtmlString()
                );
        });
        column.Settings.AllowDragDrop = DefaultBoolean.False;
        column.Settings.AllowSort = DefaultBoolean.False;
        column.Width = 70;
    });
    settings.Settings.ShowGroupPanel = true;
    settings.KeyFieldName = "CarId";
    settings.ClientSideEvents.BeginCallback = "carFilter.onBeginCallback";
    settings.SettingsPager.PageSize = 15;
}).Bind(Model).GetHtml()

AutoSiteProject/AutoSiteProject.UI/Views/DataLoader/GetCarItemsPartial.cshtml
@using System.Web.UI.WebControls
@using AutoSiteProject.Models.ViewModels
@using Microsoft.AspNet.Identity
@model IEnumerable<CarAggregateViewModel>

@Html.DevExpress().GridView(settings =>
{
    settings.Name = "carsGridView";
    settings.CallbackRouteValues = new { Controller = "DataLoader", Action = "GetCarItemsPartial" };
    settings.Width = Unit.Percentage(100);

    if (User.IsInRole("Admin")) settings.Columns.Add("CarId");

    settings.Columns.Add("Country");
    settings.Columns.Add("Manufacturer");
    settings.Columns.Add("Model");
    settings.Columns.Add("BodyType", "Body type");
    settings.Columns.Add("FuelType", "Fuel type");
    settings.Columns.Add("TransmitionType", "Transmition type");
    settings.Columns.Add("Price");
    settings.Columns.Add("ReleaseYear", "Release year");
    settings.Columns.Add("Volume", "Engine volume");
    settings.Columns.Add("Description");
    settings.Columns.Add("OptionsNamesString", "Options");
    if (User.IsInRole("Admin")) settings.Columns.Add("Status");
    settings.Columns.Add(column =>
    {
        column.Caption = "#";
        column.SetDataItemTemplateContent(c =>
        {
            ViewContext.Writer.Write(
             Html.ActionLink("Details", "Details", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
             + "&nbsp;");
            var userId = User.Identity.GetUserId();
            if ((DataBinder.Eval(c.DataItem, "OwnerId").ToString() == userId && ((CarItemStatus)DataBinder.Eval(c.DataItem, "Status")) == CarItemStatus.Open) || User.IsInRole("Admin"))
                ViewContext.Writer.Write(
                        Html.ActionLink("Edit", "Edit", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        + "&nbsp;" +
                        Html.ActionLink("Close", "SetStatusToClose", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        );
            if (User.IsInRole("Admin"))
                ViewContext.Writer.Write(
                        "&nbsp;" +
                        Html.ActionLink("Delete", "Delete", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        );
        });
        column.SetHeaderTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("New", "Create", "CarItem").ToHtmlString()
                );
        });
        column.Settings.AllowDragDrop = DefaultBoolean.False;
        column.Settings.AllowSort = DefaultBoolean.False;
        column.Width = 70;
    });
    settings.KeyFieldName = "CarId";
    settings.SettingsPager.PageSize = 15;
}).Bind(Model).GetHtml()

AutoSiteProject/AutoSiteProject.UI/Views/DataLoader/GetCarModelsPartial.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<AutoSiteProject.Models.ViewModels.CarModelViewModel>

@Html.DevExpress().GridView(settings =>
{
    settings.Name = "carModelsGridView";
    settings.CallbackRouteValues = new { Controller = "DataLoader", Action = "GetCarModelsPartial" };
    settings.Width = Unit.Percentage(100);
    settings.Columns.Add(column =>
    {
        column.Caption = "#";
        column.SetDataItemTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("Edit", "Edit", "CarModel", routeValues: new { Id = DataBinder.Eval(c.DataItem, "Id") }, htmlAttributes: new { })
                + "&nbsp;" +
                Html.ActionLink("Delete", "Delete", "CarModel", routeValues: new { Id = DataBinder.Eval(c.DataItem, "Id") }, htmlAttributes: new { })
                );
        });
        column.SetHeaderTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("New", "Create", "CarModel").ToHtmlString()
                );
        });
        column.Settings.AllowDragDrop = DefaultBoolean.False;
        column.Settings.AllowSort = DefaultBoolean.False;
        column.Width = 70;
    });
    settings.Columns.Add("Id");
    settings.Columns.Add("Name");
    settings.Columns.Add("Manufacturer");
    settings.KeyFieldName = "Id";
    settings.SettingsPager.PageSize = 25;

}).Bind(Model).GetHtml()

AutoSiteProject/AutoSiteProject.UI/Views/DataLoader/GetRolesPartial.cshtml
@using System.Web.UI.WebControls
@using AutoSiteProject.Models.ViewModels
@model IEnumerable<RoleViewModel>

@Html.DevExpress().GridView(settings =>
{
    settings.Name = "rolesGridView";
    settings.CallbackRouteValues = new { Controller = "DataLoader", Action = "GetRolesPartial" };
    settings.Width = Unit.Percentage(100);

    settings.Columns.Add("Name");
    settings.Columns.Add("Description");
    settings.Columns.Add(column =>
    {
        column.Caption = "#";
        column.SetDataItemTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("Edit", "Edit", "Role", routeValues: new { Id = DataBinder.Eval(c.DataItem, "Id") }, htmlAttributes: new { })
                + "&nbsp;" +
                Html.ActionLink("Delete", "Delete", "Role", routeValues: new { Id = DataBinder.Eval(c.DataItem, "Id") }, htmlAttributes: new { })
                );
        });
        column.SetHeaderTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("New", "Create", "Role").ToHtmlString()
                );
        });
        column.Settings.AllowDragDrop = DefaultBoolean.False;
        column.Settings.AllowSort = DefaultBoolean.False;
        column.Width = 70;
    });
    settings.KeyFieldName = "Id";
}).Bind(Model).GetHtml()

AutoSiteProject/AutoSiteProject.UI/Views/DataLoader/MyCarsListPartial.cshtml
@using System.Web.UI.WebControls
@using AutoSiteProject.Models.ViewModels
@using Microsoft.AspNet.Identity
@model IEnumerable<CarAggregateViewModel>

@Html.DevExpress().GridView(settings =>
{
    settings.Name = "myCarsGridView";
    settings.CallbackRouteValues = new { Controller = "DataLoader", Action = "MyCarsListPartial" };
    settings.Width = Unit.Percentage(100);

    if (User.IsInRole("Admin")) settings.Columns.Add("CarId");

    settings.Columns.Add("Country");
    settings.Columns.Add("Manufacturer");
    settings.Columns.Add("Model");
    settings.Columns.Add("BodyType", "Body type");
    settings.Columns.Add("FuelType", "Fuel type");
    settings.Columns.Add("TransmitionType", "Transmition type");
    settings.Columns.Add("Price");
    settings.Columns.Add("ReleaseYear", "Release year");
    settings.Columns.Add("Volume", "Engine volume");
    settings.Columns.Add("Description");
    settings.Columns.Add("OptionsNamesString", "Options");
    settings.Columns.Add("Status", "Status");
    settings.Columns.Add(column =>
    {
        column.Caption = "#";
        column.SetDataItemTemplateContent(c =>
        {
            ViewContext.Writer.Write(
             Html.ActionLink("Details", "Details", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
             + "&nbsp;");
            var userId = User.Identity.GetUserId();
            if ((DataBinder.Eval(c.DataItem, "OwnerId").ToString() == userId && ((CarItemStatus)DataBinder.Eval(c.DataItem, "Status")) == CarItemStatus.Open) || User.IsInRole("Admin"))
                ViewContext.Writer.Write(
                        Html.ActionLink("Edit", "Edit", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        + "&nbsp;" +
                        Html.ActionLink("Close", "SetStatusToClose", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        );
            if (User.IsInRole("Admin"))
                ViewContext.Writer.Write(
                        "&nbsp;" +
                        Html.ActionLink("Delete", "Delete", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        );
        });
        column.SetHeaderTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("New", "Create", "CarItem").ToHtmlString()
                );
        });
        column.Settings.AllowDragDrop = DefaultBoolean.False;
        column.Settings.AllowSort = DefaultBoolean.False;
        column.Width = 70;
    });
    settings.KeyFieldName = "CarId";
    settings.SettingsPager.PageSize = 15;
}).Bind(Model).GetHtml()